[versions]

paper = "1.20.4-R0.1-SNAPSHOT"
kyori = "4.21.0"
nbt_api = "2.15.0"

[libraries]

# Minecraft
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Adventure
kyori = { module = "net.kyori:adventure-api", version.ref = "kyori" }
kyori-mm = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori" }

# Misc
nbt_api = { module = "de.tr7zw:item-nbt-api", version.ref = "nbt_api" }

# Holograms
holographic_displays = { module = "me.filoghost.holographicdisplays:holographicdisplays-api", version = "3.0.1" }
decent_holograms = { module = "com.github.decentsoftware-eu:decentholograms", version = "2.8.1" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.6" }

# Item Plugins
itemsadder_api = { module = "com.github.LoneDev6:api-itemsadder", version = "3.6.1" }
